### ISSUE TITLE
Traffic is not forwarded to clients

### ISSUE THREAD

**Issue by Ferohers** [Gorodskih/docker_strongswan_ikev2_letsencrypt#1]
Hello all is good and well (docker container works well and clients can connect)

The issue is that clients cannot access internet later on.

**Comment by Gorodskih** [comment]
Hello! What app do your clients use to connect to the server? Which operating system?
Do they have IPv4 internet access or IPv6? (Currently IPv6 is actually not forwarded)

**Comment by Ferohers** [comment]
Please do not change      - ETH_DEVICE=eth0
My bad.
